name: Build 

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  haskell:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build
